# Generated by Django 5.2.16 on 2026-08-04 04:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion_colectivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudcolectivo',
            options={'ordering': ('-created_at',), 'permissions': (('view_requests', 'Puede ver solicitudes de Colectivos'), ('create_requests', 'Puede crear solicitudes de Colectivos'), ('edit_requests', 'Puede editar borradores de Colectivos'), ('assign_requests', 'Puede asignar solicitudes de Colectivos'), ('approve_requests', 'Puede aprobar solicitudes de Colectivos'), ('close_requests', 'Puede cerrar solicitudes de Colectivos'), ('cancel_requests', 'Puede cancelar solicitudes de Colectivos'), ('export_excel', 'Puede exportar Excel de Colectivos'), ('view_economic_data', 'Puede ver información económica de Colectivos'), ('view_personal_data', 'Puede ver datos personales de Colectivos'), ('manage_notifications', 'Puede gestionar notificaciones de Colectivos'), ('generate_external_access', 'Puede generar accesos externos'), ('send_requests', 'Puede enviar solicitudes externas'), ('regenerate_external_access', 'Puede regenerar accesos externos'), ('view_responses', 'Puede ver respuestas externas'), ('review_responses', 'Puede revisar respuestas externas'), ('request_corrections', 'Puede solicitar correcciones'), ('approve_responses', 'Puede aprobar respuestas'), ('download_attachments', 'Puede descargar adjuntos'), ('import_excel', 'Puede importar Excel de novedades'), ('export_response', 'Puede exportar respuestas'), ('export_comparison', 'Puede exportar comparativos'), ('export_approved', 'Puede exportar consolidados aprobados'))},
        ),
        migrations.AddField(
            model_name='solicitudcolectivoregistro',
            name='public_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.CreateModel(
            name='AccesoExternoSolicitudColectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(editable=False, max_length=32, unique=True)),
                ('token_hash', models.CharField(editable=False, max_length=64)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('VERIFICADO', 'Verificado'), ('USADO', 'Usado'), ('EXPIRADO', 'Expirado'), ('REVOCADO', 'Revocado'), ('BLOQUEADO', 'Bloqueado')], db_index=True, default='ACTIVO', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('first_access_at', models.DateTimeField(blank=True, null=True)),
                ('last_access_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('used_for_submission_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('encrypted_recipient', models.TextField()),
                ('recipient_hash', models.CharField(db_index=True, max_length=64)),
                ('encrypted_contact_name', models.TextField(blank=True)),
                ('encrypted_intro', models.TextField(blank=True)),
                ('encrypted_instructions', models.TextField(blank=True)),
                ('channel', models.CharField(default='EMAIL', max_length=16)),
                ('purpose', models.CharField(default='CLIENT_RESPONSE', max_length=32)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('safe_metadata', models.JSONField(blank=True, default=dict)),
                ('otp_hash', models.CharField(blank=True, editable=False, max_length=128)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('otp_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos_colectivos_creados', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_accesses', to='cotizacion_colectivos.solicitudcolectivo')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accesos_colectivos_revocados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaSolicitudColectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('SUPERADA', 'Superada'), ('APROBADA', 'Aprobada')], db_index=True, default='BORRADOR', max_length=12)),
                ('origin', models.CharField(choices=[('WEB', 'Formulario web'), ('EXCEL', 'Excel')], max_length=8)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('checksum', models.CharField(max_length=64)),
                ('encrypted_client_observations', models.TextField(blank=True)),
                ('declaration_confirmed', models.BooleanField(default=False)),
                ('form_version', models.PositiveSmallIntegerField(default=1)),
                ('safe_metadata', models.JSONField(blank=True, default=dict)),
                ('access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='cotizacion_colectivos.accesoexternosolicitudcolectivo')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='cotizacion_colectivos.solicitudcolectivo')),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='CambioSolicitudColectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SIN_CAMBIOS', 'Sin cambios'), ('MODIFICAR', 'Modificar'), ('RETIRAR', 'Retirar'), ('INCLUIR', 'Incluir')], max_length=16)),
                ('functional_field', models.CharField(max_length=64)),
                ('encrypted_previous_value', models.TextField(blank=True)),
                ('encrypted_new_value', models.TextField(blank=True)),
                ('validation_status', models.CharField(choices=[('VALIDO', 'Válido'), ('ADVERTENCIA', 'Advertencia'), ('INVALIDO', 'Inválido')], default='VALIDO', max_length=12)),
                ('safe_error', models.CharField(blank=True, max_length=80)),
                ('encrypted_observation', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField()),
                ('encrypted_branch_payload', models.TextField(blank=True)),
                ('checksum', models.CharField(max_length=64)),
                ('original_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='response_changes', to='cotizacion_colectivos.solicitudcolectivoregistro')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='cotizacion_colectivos.respuestasolicitudcolectivo')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AdjuntoSolicitudColectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe_original_name', models.CharField(max_length=120)),
                ('internal_name', models.CharField(max_length=80, unique=True)),
                ('extension', models.CharField(max_length=8)),
                ('detected_mime', models.CharField(max_length=80)),
                ('size', models.PositiveIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('REVISION_ANTIVIRUS', 'Pendiente de revisión antivirus'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='REVISION_ANTIVIRUS', max_length=24)),
                ('category', models.CharField(default='SOPORTE', max_length=32)),
                ('stored_path', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by_external', models.BooleanField(default=True)),
                ('safe_metadata', models.JSONField(blank=True, default=dict)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cotizacion_colectivos.solicitudcolectivo')),
                ('change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='cotizacion_colectivos.cambiosolicitudcolectivo')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cotizacion_colectivos.respuestasolicitudcolectivo')),
            ],
        ),
        migrations.CreateModel(
            name='RevisionSolicitudColectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APROBAR', 'Aprobar'), ('RECHAZAR', 'Rechazar'), ('REQUIERE_CORRECCION', 'Requiere corrección'), ('APROBAR_CON_AJUSTE', 'Aprobar con ajuste')], max_length=24)),
                ('encrypted_approved_value', models.TextField(blank=True)),
                ('encrypted_internal_observation', models.TextField(blank=True)),
                ('encrypted_client_observation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('checksum', models.CharField(max_length=64)),
                ('change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='cotizacion_colectivos.cambiosolicitudcolectivo')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cotizacion_colectivos.solicitudcolectivo')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='cotizacion_colectivos.respuestasolicitudcolectivo')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='accesoexternosolicitudcolectivo',
            index=models.Index(fields=['request', 'status'], name='colect_access_request'),
        ),
        migrations.AddConstraint(
            model_name='respuestasolicitudcolectivo',
            constraint=models.UniqueConstraint(fields=('request', 'version'), name='colect_response_version'),
        ),
        migrations.AddConstraint(
            model_name='revisionsolicitudcolectivo',
            constraint=models.UniqueConstraint(fields=('response', 'change', 'version'), name='colect_review_change_version'),
        ),
    ]
