# Generated by Django 5.2.16 on 2026-08-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion_colectivos', '0004_vistapreviaexcelsolicitudcolectivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudcolectivo',
            options={'ordering': ('-created_at',), 'permissions': (('view_requests', 'Puede ver solicitudes de Colectivos'), ('create_requests', 'Puede crear solicitudes de Colectivos'), ('edit_requests', 'Puede editar borradores de Colectivos'), ('assign_requests', 'Puede asignar solicitudes de Colectivos'), ('approve_requests', 'Puede aprobar solicitudes de Colectivos'), ('close_requests', 'Puede cerrar solicitudes de Colectivos'), ('cancel_requests', 'Puede cancelar solicitudes de Colectivos'), ('export_excel', 'Puede exportar Excel de Colectivos'), ('view_economic_data', 'Puede ver información económica de Colectivos'), ('view_personal_data', 'Puede ver datos personales de Colectivos'), ('manage_notifications', 'Puede gestionar notificaciones de Colectivos'), ('generate_external_access', 'Puede generar accesos externos'), ('send_requests', 'Puede enviar solicitudes externas'), ('regenerate_external_access', 'Puede regenerar accesos externos'), ('revoke_external_access', 'Puede revocar accesos externos'), ('view_responses', 'Puede ver respuestas externas'), ('review_responses', 'Puede revisar respuestas externas'), ('request_corrections', 'Puede solicitar correcciones'), ('approve_responses', 'Puede aprobar respuestas'), ('download_attachments', 'Puede descargar adjuntos'), ('import_excel', 'Puede importar Excel de novedades'), ('export_response', 'Puede exportar respuestas'), ('export_comparison', 'Puede exportar comparativos'), ('export_approved', 'Puede exportar consolidados aprobados'))},
        ),
    ]
