# Generated by Django 5.2.16 on 2026-09-08 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion_colectivos', '0022_novedadingresozho_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingExceptionRefreshRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(default='production', max_length=12)),
                ('as_of', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En curso'), ('SUCCESS', 'Completada'), ('FAILED', 'Fallida')], db_index=True, default='PENDING', max_length=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('safe_error', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'ordering': ('-requested_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='BillingOperationalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_key', models.CharField(max_length=500, unique=True)),
                ('kind', models.CharField(choices=[('OPERATION', 'Operación'), ('MISSING_OPERATION', 'Operación faltante'), ('POLICY_GAP', 'Cobro faltante')], max_length=24)),
                ('policy_id', models.CharField(blank=True, max_length=40)),
                ('policy_number', models.CharField(db_index=True, max_length=120)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('insurer', models.CharField(blank=True, db_index=True, max_length=255)),
                ('branch', models.CharField(blank=True, db_index=True, max_length=160)),
                ('analyst', models.CharField(blank=True, max_length=160)),
                ('operation_id', models.CharField(blank=True, max_length=40)),
                ('operation_name', models.CharField(blank=True, max_length=255)),
                ('installment_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('relevant_date', models.DateField(blank=True, null=True)),
                ('billing_date', models.DateField(blank=True, null=True)),
                ('local_priority', models.PositiveSmallIntegerField(db_index=True)),
                ('detection_status', models.CharField(choices=[('DETECTED', 'Detectado'), ('NOT_DETECTED', 'Ya no detectado')], db_index=True, default='DETECTED', max_length=16)),
                ('first_detected_at', models.DateTimeField()),
                ('last_detected_at', models.DateTimeField()),
                ('detection_count', models.PositiveIntegerField(default=1)),
                ('reappearance_count', models.PositiveIntegerField(default=0)),
                ('zoho_task_id', models.CharField(blank=True, max_length=40)),
                ('zoho_task_status', models.CharField(blank=True, max_length=120)),
                ('zoho_task_responsible', models.CharField(blank=True, max_length=160)),
                ('zoho_task_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('local_priority', 'relevant_date', 'policy_number', 'case_key'),
                'permissions': (('view_billing_exceptions', 'Puede ver Excepciones de Facturación'), ('refresh_billing_exceptions', 'Puede actualizar Excepciones de Facturación'), ('manage_billing_exception_tasks', 'Puede gestionar Tasks de Excepciones de Facturación')),
            },
        ),
        migrations.CreateModel(
            name='BillingTechnicalException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_key', models.CharField(max_length=500, unique=True)),
                ('source', models.CharField(max_length=40)),
                ('exception_type', models.CharField(db_index=True, max_length=40)),
                ('rule_code', models.CharField(max_length=120)),
                ('reason', models.CharField(max_length=500)),
                ('source_reference', models.CharField(max_length=255)),
                ('policy_id', models.CharField(blank=True, max_length=40)),
                ('policy_number', models.CharField(db_index=True, max_length=120)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('insurer', models.CharField(blank=True, db_index=True, max_length=255)),
                ('branch', models.CharField(blank=True, db_index=True, max_length=160)),
                ('analyst', models.CharField(blank=True, max_length=160)),
                ('operation_id', models.CharField(blank=True, max_length=40)),
                ('operation_name', models.CharField(blank=True, max_length=255)),
                ('installment_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('relevant_date', models.DateField(blank=True, null=True)),
                ('billing_date', models.DateField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('detection_status', models.CharField(choices=[('DETECTED', 'Detectada'), ('NOT_DETECTED', 'Ya no detectada')], db_index=True, default='DETECTED', max_length=16)),
                ('first_detected_at', models.DateTimeField()),
                ('last_detected_at', models.DateTimeField()),
                ('detection_count', models.PositiveIntegerField(default=1)),
                ('reappearance_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('exception_key',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='colectivostaskoutbox',
            name='colect_task_outbox_one_source',
        ),
        migrations.AlterField(
            model_name='colectivostaskoutbox',
            name='event_kind',
            field=models.CharField(max_length=24),
        ),
        migrations.AddField(
            model_name='billingexceptionrefreshrun',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_exception_refreshes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingoperationalcase',
            name='last_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_cases', to='cotizacion_colectivos.billingexceptionrefreshrun'),
        ),
        migrations.AddField(
            model_name='colectivostaskoutbox',
            name='billing_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_outbox', to='cotizacion_colectivos.billingoperationalcase'),
        ),
        migrations.AddConstraint(
            model_name='colectivostaskoutbox',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('billing_case__isnull', True), ('quotation__isnull', True), ('request__isnull', False)), models.Q(('billing_case__isnull', True), ('quotation__isnull', False), ('request__isnull', True)), models.Q(('billing_case__isnull', False), ('quotation__isnull', True), ('request__isnull', True)), _connector='OR'), name='colect_task_outbox_one_source'),
        ),
        migrations.AddField(
            model_name='billingtechnicalexception',
            name='last_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technical_exceptions', to='cotizacion_colectivos.billingexceptionrefreshrun'),
        ),
        migrations.AddField(
            model_name='billingoperationalcase',
            name='exceptions',
            field=models.ManyToManyField(related_name='operational_cases', to='cotizacion_colectivos.billingtechnicalexception'),
        ),
        migrations.AddConstraint(
            model_name='billingexceptionrefreshrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING', 'RUNNING'))), fields=('profile',), name='colect_bill_one_active_run'),
        ),
        migrations.AddIndex(
            model_name='billingtechnicalexception',
            index=models.Index(fields=['detection_status', 'exception_type'], name='colect_bill_exc_state_type'),
        ),
        migrations.AddIndex(
            model_name='billingtechnicalexception',
            index=models.Index(fields=['policy_id', 'operation_id'], name='colect_bill_exc_subject'),
        ),
        migrations.AddIndex(
            model_name='billingoperationalcase',
            index=models.Index(fields=['detection_status', 'local_priority'], name='colect_bill_case_state_pri'),
        ),
        migrations.AddIndex(
            model_name='billingoperationalcase',
            index=models.Index(fields=['zoho_task_id'], name='colect_bill_case_task'),
        ),
    ]
