from django.conf import settings
from django.db import migrations, models
import django.core.validators

class Migration(migrations.Migration):
    initial = True
    dependencies = [("auth", "0012_alter_user_first_name_max_length")]
    operations = [
        migrations.CreateModel(name="InboundEmail", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("source_mailbox", models.EmailField(max_length=254)), ("external_message_id", models.CharField(max_length=500)), ("conversation_id", models.CharField(blank=True, max_length=500)), ("received_at", models.DateTimeField()), ("from_name", models.CharField(blank=True, max_length=255)), ("from_email", models.EmailField(blank=True, max_length=254)), ("from_domain", models.CharField(blank=True, max_length=255)), ("to", models.JSONField(blank=True, default=list)), ("cc", models.JSONField(blank=True, default=list)), ("subject", models.CharField(blank=True, max_length=998)), ("body_text", models.TextField(blank=True)), ("has_attachments", models.BooleanField(default=False)), ("created_at", models.DateTimeField(auto_now_add=True))], options={"ordering": ["-received_at", "-pk"]}),
        migrations.CreateModel(name="EmailPolicyProfile", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("code", models.CharField(max_length=80)), ("source_mailbox", models.EmailField(max_length=254, unique=True)), ("version", models.CharField(max_length=32)), ("status", models.CharField(choices=[("ACTIVE", "Activa"), ("REVIEW_ONLY", "Solo revisión"), ("INACTIVE", "Inactiva")], default="INACTIVE", max_length=20)), ("active", models.BooleanField(default=False)), ("created_at", models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name="EmailException", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("last_subject", models.CharField(blank=True, max_length=998)), ("organization", models.CharField(blank=True, max_length=120)), ("family", models.CharField(blank=True, max_length=120)), ("event_type", models.CharField(blank=True, max_length=120)), ("exception_reason", models.CharField(blank=True, max_length=500)), ("confidence", models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])), ("rule_id", models.CharField(blank=True, max_length=120)), ("correlation_key", models.CharField(blank=True, max_length=255)), ("classification_details", models.JSONField(blank=True, default=dict)), ("status", models.CharField(choices=[("PENDING", "Pendiente"), ("MANAGED", "Gestionada"), ("IGNORED", "Ignorada"), ("ERROR", "Error")], default="PENDING", max_length=12)), ("detected_at", models.DateTimeField(auto_now_add=True)), ("handled_at", models.DateTimeField(blank=True, null=True)), ("ignored_reason", models.CharField(blank=True, max_length=80)), ("ignored_comment", models.TextField(blank=True)), ("error_code", models.CharField(blank=True, max_length=80)), ("handled_by", models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name="email_exceptions_handled", to=settings.AUTH_USER_MODEL)), ("policy_profile", models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, to="email_exceptions.emailpolicyprofile")), ("primary_email", models.ForeignKey(on_delete=models.deletion.PROTECT, related_name="primary_exceptions", to="email_exceptions.inboundemail"))]),
        migrations.CreateModel(name="EmailAttachment", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("filename", models.CharField(max_length=255)), ("content_type", models.CharField(blank=True, max_length=160)), ("size", models.PositiveBigIntegerField(default=0)), ("file", models.FileField(blank=True, upload_to="email_exceptions/%Y/%m/")), ("checksum", models.CharField(blank=True, max_length=64)), ("is_inline", models.BooleanField(default=False)), ("is_documental", models.BooleanField(default=False)), ("email", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="attachments", to="email_exceptions.inboundemail"))]),
        migrations.CreateModel(name="EmailExceptionMessage", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("linked_at", models.DateTimeField(auto_now_add=True)), ("email", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="exception_links", to="email_exceptions.inboundemail")), ("exception", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="messages", to="email_exceptions.emailexception"))]),
        migrations.CreateModel(name="EmailAuditEvent", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("event_type", models.CharField(max_length=40)), ("timestamp", models.DateTimeField(auto_now_add=True)), ("metadata", models.JSONField(blank=True, default=dict)), ("actor", models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ("exception", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="audit_events", to="email_exceptions.emailexception"))]),
        migrations.CreateModel(name="ZohoTaskCreation", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("task_id", models.CharField(blank=True, max_length=80)), ("task_url", models.URLField(blank=True)), ("zoho_owner_id", models.CharField(blank=True, max_length=120)), ("zoho_owner_name", models.CharField(blank=True, max_length=255)), ("subject", models.CharField(max_length=255)), ("due_date", models.DateField(blank=True, null=True)), ("description", models.TextField(blank=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("technical_status", models.CharField(default="PENDING", max_length=30)), ("created_by", models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ("exception", models.OneToOneField(on_delete=models.deletion.CASCADE, related_name="zoho_task", to="email_exceptions.emailexception"))]),
        migrations.AddConstraint(model_name="inboundemail", constraint=models.UniqueConstraint(fields=("source_mailbox", "external_message_id"), name="email_unique_source_message")),
        migrations.AddConstraint(model_name="emailpolicyprofile", constraint=models.UniqueConstraint(fields=("code", "version"), name="email_unique_policy_version")),
        migrations.AddConstraint(model_name="emailexceptionmessage", constraint=models.UniqueConstraint(fields=("exception", "email"), name="email_unique_exception_message")),
    ]
