# Generated by Django 5.2.16 on 2026-09-12 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_exceptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailauditevent',
            options={'ordering': ['timestamp', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='emailexception',
            options={'ordering': ['-detected_at', '-pk']},
        ),
        migrations.AddIndex(
            model_name='emailexception',
            index=models.Index(fields=['status', 'detected_at'], name='email_excep_status_ba8fec_idx'),
        ),
        migrations.AddIndex(
            model_name='emailexception',
            index=models.Index(fields=['organization', 'event_type'], name='email_excep_organiz_684321_idx'),
        ),
        migrations.AddIndex(
            model_name='emailexception',
            index=models.Index(fields=['correlation_key'], name='email_excep_correla_fdf4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundemail',
            index=models.Index(fields=['source_mailbox', 'received_at'], name='email_excep_source__8b4525_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundemail',
            index=models.Index(fields=['conversation_id'], name='email_excep_convers_45c129_idx'),
        ),
    ]
