# Generated by Django 5.2.16 on 2026-09-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_exceptions', '0004_exceptioncase_casemessage_emailexception_case'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailexception',
            options={'ordering': ['-detected_at', '-pk'], 'permissions': (('view_email_exceptions_operational', 'Can view operational email exceptions and cases'), ('operate_email_exceptions', 'Can perform operational email exception actions'))},
        ),
    ]
