# Generated by Django 5.2.16 on 2026-09-16 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_exceptions', '0005_alter_emailexception_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptioncase',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceptioncase',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierto'), ('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En gestión'), ('WAITING', 'En espera'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=12),
        ),
        migrations.CreateModel(
            name='CaseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CASE_CREATED', 'Caso creado'), ('STATUS_CHANGED', 'Estado cambiado'), ('RESOLVED', 'Caso resuelto'), ('CLOSED', 'Caso cerrado'), ('REOPENED', 'Caso reabierto')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(blank=True, max_length=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_case_activities', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='email_exceptions.exceptioncase')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['case', 'created_at'], name='email_excep_case_id_10c144_idx')],
            },
        ),
    ]
