# Generated by Django 5.2.16 on 2026-09-16 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_exceptions', '0006_exceptioncase_closed_at_alter_exceptioncase_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptioncase',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceptioncase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_email_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exceptioncase',
            name='follow_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceptioncase',
            name='next_action',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='caseactivity',
            name='event_type',
            field=models.CharField(choices=[('CASE_CREATED', 'Caso creado'), ('STATUS_CHANGED', 'Estado cambiado'), ('RESOLVED', 'Caso resuelto'), ('CLOSED', 'Caso cerrado'), ('REOPENED', 'Caso reabierto'), ('ASSIGNED', 'Caso asignado'), ('REASSIGNED', 'Caso reasignado'), ('UNASSIGNED', 'Caso desasignado'), ('FOLLOW_UP_UPDATED', 'Seguimiento actualizado'), ('NOTE_ADDED', 'Nota interna añadida')], max_length=24),
        ),
    ]
