from django.urls import path

from . import views

app_name = "cotizacion_colectivos"
urlpatterns = [
    path("", views.index, name="index"),
    path("empresas/buscar/", views.company_search, name="company_search"),
    path("empresas/<str:token>/", views.company_detail, name="company_detail"),
    path("individuos/buscar/", views.person_search, name="person_search"),
    path("individuos/<str:token>/", views.person_detail, name="person_detail"),
    path("solicitudes/construir/<str:source_kind>/<str:token>/", views.request_builder, name="request_builder"),
    path("polizas/<str:token>/", views.policy_detail, name="policy_detail"),
    path("polizas/<str:token>/grupo/", views.policy_group, name="policy_group"),
    path("polizas/<str:token>/actualizar/", views.policy_refresh_preparation, name="policy_refresh_preparation"),
    path("polizas/<str:token>/excel/", views.policy_excel, name="policy_excel"),
    path("polizas/<str:token>/plantillas-invitacion/", views.policy_invitation_preview, name="policy_invitation_preview"),
    path("polizas/<str:token>/plantillas-invitacion/descargar/", views.policy_invitation_download, name="policy_invitation_download"),
    path("polizas/<str:token>/enlace/", views.policy_generate_access, name="policy_generate_access_simple"),
    path("polizas/<str:token>/enlace/revocar/", views.policy_revoke_access, name="policy_revoke_access"),
    path("polizas/<str:token>/enlace/<str:request_type>/", views.policy_generate_access, name="policy_generate_access"),
    path("polizas/<str:token>/solicitudes/crear/", views.request_create, name="request_create"),
    path("solicitudes/", views.request_list, name="request_list"),
    path("solicitudes/<str:public_id>/", views.request_detail, name="request_detail"),
    path("solicitudes/<str:public_id>/estado/", views.request_transition, name="request_transition"),
    path("solicitudes/<str:public_id>/editar/", views.request_edit, name="request_edit"),
    path("solicitudes/<str:public_id>/regenerar-snapshot/", views.request_regenerate_snapshot, name="request_regenerate_snapshot"),
    path("solicitudes/<str:public_id>/acceso-externo/", views.request_external_access, name="request_external_access"),
    path("solicitudes/<str:public_id>/acceso-externo/regenerar/", views.request_external_access, {"regenerate": True}, name="request_external_access_regenerate"),
    path("solicitudes/<str:public_id>/acceso-externo/correo/", views.request_external_access_email, name="request_external_access_email"),
    path("solicitudes/<str:public_id>/acceso-externo/regenerar-directo/", views.request_external_access_quick_regenerate, name="request_external_access_quick_regenerate"),
    path("solicitudes/<str:public_id>/acceso-externo/revocar/", views.request_external_access_revoke, name="request_external_access_revoke"),
    path("solicitudes/<str:public_id>/excel/plantilla/", views.request_novelties_template, name="request_novelties_template"),
    path("solicitudes/<str:public_id>/respuestas/<int:version>/", views.response_review, name="response_review"),
    path("respuestas/<str:public_id>/<int:version>/", views.response_detail, name="response_detail"),
    path("solicitudes/<str:public_id>/respuestas/<int:version>/comparativo/", views.response_comparison, name="response_comparison"),
    path("solicitudes/<str:public_id>/respuestas/<int:version>/exportar/", views.response_export, name="response_export"),
    path("solicitudes/<str:public_id>/respuestas/<int:version>/consolidado/", views.response_approved_export, name="response_approved_export"),
    path("solicitudes/<str:public_id>/adjuntos/<int:attachment_id>/", views.attachment_download, name="attachment_download"),
    path("notificaciones/", views.notification_list, name="notification_list"),
    path("notificaciones/<int:notification_id>/leer/", views.notification_read, name="notification_read"),
    path("notificaciones/leer-todas/", views.notifications_read_all, name="notifications_read_all"),
]
