from ays_zoho_sdk.constants import (
    API_VERSION,
    DEFAULT_SCOPES,
    MAX_COQL_LENGTH,
    MAX_COQL_RECORDS,
    MAX_FIELDS_PER_REQUEST,
    MAX_RECORDS_PER_REQUEST,
    TOKEN_EXPIRY_MARGIN_SECONDS,
    USER_AGENT,
)

__all__ = [
    "API_VERSION",
    "DEFAULT_SCOPES",
    "MAX_COQL_LENGTH",
    "MAX_COQL_RECORDS",
    "MAX_FIELDS_PER_REQUEST",
    "MAX_RECORDS_PER_REQUEST",
    "TOKEN_EXPIRY_MARGIN_SECONDS",
    "USER_AGENT",
]
