from django.urls import path
from . import views
from . import security_views
from . import control_views
from . import report_views
app_name='vault'
urlpatterns=[path('vault/',views.dashboard,name='dashboard'),path('vault/cards/',views.card_list,name='card_list'),path('vault/cards/new/',views.card_create,name='card_create'),path('vault/cards/<int:pk>/',views.card_detail,name='card_detail'),path('vault/cards/<int:pk>/edit/',views.card_edit,name='card_edit'),path('vault/cards/<int:pk>/deactivate/',views.card_deactivate,name='card_deactivate'),path('vault/cards/<int:pk>/reveal/',views.reveal,name='reveal'),path('vault/cards/<int:pk>/copy-event/',views.copy_event,name='copy_event'),path('vault/protected/reauthenticate/',views.protected_reauthenticate,name='protected_reauthenticate'),path('vault/protected/confirm/',views.protected_confirm,name='protected_confirm'),path('vault/audit/',views.audit_list,name='audit')]
urlpatterns += [path('security/reauthenticate/',security_views.reauthenticate,name='reauthenticate'),path('security/sessions/',security_views.session_list,name='sessions'),path('security/sessions/revoke-all/',security_views.session_revoke_all,name='session_revoke_all'),path('security/sessions/<int:pk>/revoke/',security_views.session_revoke,name='session_revoke'),path('security/admin/users/',security_views.identity_user_list,name='identity_users'),path('security/admin/users/<int:user_id>/sessions/',security_views.admin_session_list,name='admin_sessions'),path('security/admin/users/<int:user_id>/sessions/revoke-all/',security_views.admin_session_revoke_all,name='admin_session_revoke_all'),path('security/admin/sessions/<int:pk>/revoke/',security_views.admin_session_revoke,name='admin_session_revoke'),path('security/devices/',security_views.device_list,name='devices'),path('security/devices/<int:pk>/<str:action>/',security_views.device_action,name='device_action'),path('security/admin/users/<int:user_id>/devices/',security_views.admin_device_list,name='admin_devices'),path('security/admin/devices/<int:pk>/unblock/',security_views.admin_device_unblock,name='admin_device_unblock'),path('security/admin/users/<int:user_id>/mfa-reset/',security_views.admin_mfa_reset,name='admin_mfa_reset'),path('security/mfa/recovery-codes/regenerate/',security_views.recovery_codes_regenerate,name='recovery_codes_regenerate'),path('security/alerts/',security_views.alert_list,name='alerts'),path('security/alerts/<int:pk>/',security_views.alert_detail,name='alert_detail'),path('security/password-change/',security_views.password_change,name='password_change')]
urlpatterns += [path('control/',control_views.control_center,name='control_center'),path('control/timeline/',control_views.timeline,name='timeline'),path('control/policies/',control_views.policy_settings,name='policy_settings'),path('control/exceptions/',control_views.exception_list,name='exceptions'),path('control/exceptions/<int:pk>/revoke/',control_views.exception_revoke,name='exception_revoke'),path('control/holidays/',control_views.holiday_settings,name='holidays'),path('control/recipients/',control_views.recipient_settings,name='recipients'),path('control/recipients/<int:pk>/',control_views.recipient_settings,name='recipient_edit'),path('control/notifications/<int:pk>/retry/',control_views.notification_retry,name='notification_retry')]
urlpatterns += [path('control/email/test/', control_views.email_test, name='email_test')]
urlpatterns += [path('reports/', report_views.report_center, name='report_center'), path('reports/export/<str:report_type>/<str:export_format>/', report_views.export_report, name='export_report')]
