# Generated by Django 5.2.15 on 2026-07-15 02:36

import django.db.models.deletion
import hashlib
import json
from django.conf import settings
from django.db import migrations, models


def harden_existing_identity_data(apps, schema_editor):
    AuditEvent = apps.get_model('vault', 'AuditEvent')
    AuditChainState = apps.get_model('vault', 'AuditChainState')
    RevealGrant = apps.get_model('vault', 'RevealGrant')
    SecurityAlert = apps.get_model('vault', 'SecurityAlert')
    UserProfile = apps.get_model('vault', 'UserProfile')
    RevealGrant.objects.all().delete()
    UserProfile.objects.filter(active=True).update(mfa_status='PENDING', mfa_enabled=False)
    UserProfile.objects.filter(active=False).update(mfa_status='NOT_CONFIGURED', mfa_enabled=False)
    previous_hash = ''
    sequence = 0
    for event in AuditEvent.objects.order_by('sequence'):
        sequence = event.sequence
        event.session_key = hashlib.sha256(event.session_key.encode()).hexdigest() if event.session_key and len(event.session_key) != 64 else event.session_key
        event.previous_hash = previous_hash
        canonical = json.dumps({
            'sequence': event.sequence, 'user_id': event.user_id, 'actor_role': event.actor_role,
            'action': event.action, 'card_id': event.card_id, 'field_name': event.field_name,
            'reason': event.reason, 'ip_address': str(event.ip_address or ''), 'user_agent': event.user_agent,
            'session_key': event.session_key, 'path': event.path, 'method': event.method,
            'result': event.result, 'risk_level': event.risk_level,
            'outside_office_hours': event.outside_office_hours, 'metadata': event.metadata,
            'previous_hash': event.previous_hash, 'created_at': event.created_at.isoformat(),
        }, sort_keys=True, separators=(',', ':'), ensure_ascii=False)
        event.event_hash = hashlib.sha256(canonical.encode()).hexdigest()
        event.save(update_fields=['session_key', 'previous_hash', 'event_hash'])
        previous_hash = event.event_hash
    AuditChainState.objects.update_or_create(singleton=1, defaults={'last_sequence': sequence, 'last_hash': previous_hash})
    for alert in SecurityAlert.objects.select_related('event'):
        alert.actor_id = alert.event.user_id
        alert.affected_user_id = alert.event.user_id
        alert.ip_address = alert.event.ip_address
        alert.alert_type = alert.event.action
        alert.severity = 'HIGH' if alert.event.risk_level in {'HIGH', 'CRITICAL'} else 'MEDIUM'
        alert.description = f'Evento de seguridad: {alert.event.action}'
        alert.save(update_fields=['actor', 'affected_user', 'ip_address', 'alert_type', 'severity', 'description'])


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_paymentcard_last4_index'),
        ('otp_totp', '0003_add_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securityalert',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_alerts_acted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='affected_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_alerts_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='alert_type',
            field=models.CharField(default='SECURITY_EVENT', max_length=40),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='description',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_alerts_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='safe_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mfa_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mfa_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mfa_status',
            field=models.CharField(choices=[('NOT_CONFIGURED', 'No configurado'), ('PENDING', 'Pendiente de enrolamiento'), ('ACTIVE', 'Activo'), ('BLOCKED', 'Bloqueado'), ('RECOVERY', 'Recuperación requerida')], default='NOT_CONFIGURED', max_length=24),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGIN_FAILED', 'Inicio fallido'), ('LOGOUT', 'Cierre de sesión'), ('ACCESS', 'Acceso'), ('VIEW', 'Consulta tarjeta'), ('REVEAL', 'Revelado'), ('COPY', 'Copia'), ('COPY_ATTEMPT', 'Intento de copia'), ('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DEACTIVATE', 'Desactivación'), ('DENIED', 'Acceso denegado'), ('INTEGRITY_FAILURE', 'Fallo de integridad'), ('PASSWORD_OK', 'Contraseña correcta'), ('MFA_REQUIRED', 'MFA requerido'), ('MFA_SUCCESS', 'MFA exitoso'), ('MFA_FAILED', 'MFA fallido'), ('MFA_ENROLL_START', 'Enrolamiento MFA iniciado'), ('MFA_ENROLL_COMPLETE', 'Enrolamiento MFA completado'), ('MFA_RECOVERY_USED', 'Recuperación MFA utilizada'), ('MFA_RECOVERY_REGENERATED', 'Códigos regenerados'), ('MFA_RESET', 'MFA reiniciado'), ('SESSION_CREATED', 'Sesión creada'), ('SESSION_REVOKED', 'Sesión revocada'), ('SESSION_EXPIRED', 'Sesión expirada'), ('SESSION_REPLACED', 'Sesión reemplazada'), ('DEVICE_NEW', 'Dispositivo nuevo'), ('DEVICE_TRUSTED', 'Dispositivo reconocido'), ('DEVICE_BLOCKED', 'Dispositivo bloqueado'), ('DEVICE_UNBLOCKED', 'Dispositivo desbloqueado'), ('REAUTH_SUCCESS', 'Reautenticación exitosa'), ('REAUTH_FAILED', 'Reautenticación fallida'), ('PASSWORD_CHANGED', 'Contraseña cambiada'), ('ALERT_CREATED', 'Alerta creada'), ('ALERT_REVIEWED', 'Alerta revisada'), ('ALERT_CLOSED', 'Alerta cerrada'), ('CRITICAL_BLOCKED', 'Operación crítica bloqueada')], max_length=24),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='session_key',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='revealgrant',
            name='session_key',
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.CreateModel(
            name='MFARecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(editable=False, max_length=256)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(editable=False, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('browser', models.CharField(blank=True, max_length=80)),
                ('operating_system', models.CharField(blank=True, max_length=80)),
                ('device_type', models.CharField(blank=True, max_length=40)),
                ('friendly_name', models.CharField(blank=True, max_length=100)),
                ('initial_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NEW', 'Nuevo'), ('TRUSTED', 'Reconocido'), ('BLOCKED', 'Bloqueado'), ('REVOKED', 'Revocado')], default='NEW', max_length=12)),
                ('trusted_until', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('block_reason', models.CharField(blank=True, max_length=240)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vault_devices_blocked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('encrypted_session_key', models.TextField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('initial_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('browser', models.CharField(blank=True, max_length=80)),
                ('operating_system', models.CharField(blank=True, max_length=80)),
                ('device_type', models.CharField(blank=True, max_length=40)),
                ('friendly_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('REVOKED', 'Revocada'), ('EXPIRED', 'Expirada')], default='ACTIVE', max_length=12)),
                ('revocation_reason', models.CharField(blank=True, max_length=240)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('mfa_completed', models.BooleanField(default=False)),
                ('mfa_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_reauthenticated_at', models.DateTimeField(blank=True, null=True)),
                ('new_device', models.BooleanField(default=False)),
                ('outside_office_hours', models.BooleanField(default=False)),
                ('trust_level', models.CharField(default='LOW', max_length=12)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vault_sessions_revoked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_sessions', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='vault.userdevice')),
            ],
        ),
        migrations.AddField(
            model_name='securityalert',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='vault.userdevice'),
        ),
        migrations.CreateModel(
            name='ReauthenticationGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_hash', models.CharField(editable=False, max_length=64)),
                ('purpose', models.CharField(max_length=40)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_reauth_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'session_hash', 'purpose', 'expires_at'], name='vault_reauth_lookup')],
            },
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'status'], name='vault_device_user_status'),
        ),
        migrations.AddConstraint(
            model_name='userdevice',
            constraint=models.UniqueConstraint(fields=('user', 'fingerprint_hash'), name='vault_unique_user_device'),
        ),
        migrations.AddIndex(
            model_name='securesession',
            index=models.Index(fields=['user', 'status'], name='vault_session_user_status'),
        ),
        migrations.RunPython(harden_existing_identity_data, migrations.RunPython.noop),
    ]
