# Generated by Django 5.2.15 on 2026-07-15 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_securityalert_actor_securityalert_affected_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditVerificationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('valid', models.BooleanField()),
                ('position', models.PositiveBigIntegerField(default=0)),
                ('source', models.CharField(default='COMMAND', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyEvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dry_run', models.BooleanField(default=False)),
                ('status', models.CharField(default='RUNNING', max_length=20)),
                ('checks', models.JSONField(blank=True, default=dict)),
                ('safe_error', models.CharField(blank=True, max_length=160)),
            ],
        ),
        migrations.AddField(
            model_name='securityalert',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_alerts_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='escalated_to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='idempotency_key',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='recommendation',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nueva'), ('IN_REVIEW', 'En revision'), ('REVIEWED', 'Revisada'), ('JUSTIFIED', 'Justificada'), ('ESCALATED', 'Escalada'), ('CLOSED', 'Cerrada'), ('REOPENED', 'Reabierta')], default='NEW', max_length=20),
        ),
        migrations.CreateModel(
            name='AccessException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('exception_type', models.CharField(choices=[('ALLOW', 'Permitir'), ('BLOCK', 'Bloquear'), ('EXTEND', 'Ampliar horario'), ('VACATION', 'Vacaciones o pausa operativa')], max_length=16)),
                ('role', models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('LEADER', 'Lider de cartera'), ('ANALYST', 'Analista')], max_length=10)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('daily_start', models.TimeField(blank=True, null=True)),
                ('daily_end', models.TimeField(blank=True, null=True)),
                ('operations', models.JSONField(blank=True, default=list)),
                ('reason', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('REVOKED', 'Revocada'), ('EXPIRED', 'Expirada')], default='ACTIVE', max_length=12)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=240)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vault_exceptions_created', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vault_exceptions_revoked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_access_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.AddField(
            model_name='securityalert',
            name='access_exception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='vault.accessexception'),
        ),
        migrations.CreateModel(
            name='AlertTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vault_alert_transitions', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='vault.securityalert')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=140)),
                ('national', models.BooleanField(default=True)),
                ('internal', models.BooleanField(default=False)),
                ('working_day', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vault_holidays_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('alert_types', models.JSONField(blank=True, default=list)),
                ('minimum_severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='HIGH', max_length=10)),
                ('send_start', models.TimeField(blank=True, null=True)),
                ('send_end', models.TimeField(blank=True, null=True)),
                ('delivery_mode', models.CharField(choices=[('IMMEDIATE', 'Inmediato'), ('DAILY', 'Resumen diario'), ('WEEKLY', 'Resumen semanal')], default='IMMEDIATE', max_length=12)),
                ('active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_leader', models.BooleanField(default=False)),
                ('is_alternate', models.BooleanField(default=False)),
                ('is_escalation', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vault_recipients_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=60)),
                ('masked_recipient', models.CharField(max_length=254)),
                ('recipient_hash', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('FAILED', 'Fallido'), ('RETRY', 'Reintento')], default='PENDING', max_length=12)),
                ('safe_error_code', models.CharField(blank=True, max_length=80)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('backend', models.CharField(max_length=60)),
                ('external_id', models.CharField(blank=True, max_length=160)),
                ('idempotency_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='vault.securityalert')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyConfiguration',
            fields=[
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('timezone_name', models.CharField(default='America/Bogota', max_length=64)),
                ('weekday_start', models.TimeField(default='07:00')),
                ('weekday_end', models.TimeField(default='18:00')),
                ('saturday_enabled', models.BooleanField(default=False)),
                ('saturday_start', models.TimeField(default='08:00')),
                ('saturday_end', models.TimeField(default='12:00')),
                ('sunday_enabled', models.BooleanField(default=False)),
                ('session_inactivity_minutes', models.PositiveSmallIntegerField(default=10)),
                ('maximum_sessions', models.PositiveSmallIntegerField(default=1)),
                ('new_session_policy', models.CharField(choices=[('REVOKE_PREVIOUS', 'Revocar anterior'), ('BLOCK_NEW', 'Bloquear nueva'), ('ALLOW_LIMIT', 'Permitir segun limite')], default='REVOKE_PREVIOUS', max_length=24)),
                ('reauthentication_minutes', models.PositiveSmallIntegerField(default=5)),
                ('reauthentication_operations', models.JSONField(blank=True, default=list)),
                ('outside_hours_behavior', models.CharField(choices=[('ALLOW', 'Permitir'), ('ALLOW_ALERT', 'Permitir y alertar'), ('REAUTH', 'Exigir reautenticacion'), ('BLOCK', 'Bloquear')], default='ALLOW_ALERT', max_length=20)),
                ('inactivity_login_days', models.PositiveSmallIntegerField(default=30)),
                ('inactivity_reveal_days', models.PositiveSmallIntegerField(default=30)),
                ('inactivity_copy_days', models.PositiveSmallIntegerField(default=30)),
                ('inactivity_general_days', models.PositiveSmallIntegerField(default=30)),
                ('inactive_user_days', models.PositiveSmallIntegerField(default=30)),
                ('operational_user_days', models.PositiveSmallIntegerField(default=45)),
                ('alert_review_hours', models.PositiveSmallIntegerField(default=24)),
                ('escalation_hours', models.PositiveSmallIntegerField(default=48)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vault_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='securityalert',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='vault.policyconfiguration'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['status', 'severity', 'due_at'], name='vault_alert_queue'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['alert_type', 'created_at'], name='vault_alert_type_date'),
        ),
        migrations.AddIndex(
            model_name='accessexception',
            index=models.Index(fields=['status', 'starts_at', 'ends_at'], name='vault_exception_window'),
        ),
        migrations.AddConstraint(
            model_name='accessexception',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='vault_exception_valid_period'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['date', 'working_day'], name='vault_holiday_lookup'),
        ),
        migrations.AddIndex(
            model_name='notificationrecord',
            index=models.Index(fields=['result', 'next_attempt_at'], name='vault_notify_retry'),
        ),
    ]
