# Generated by Django 5.2.15 on 2026-07-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_control_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGIN_FAILED', 'Inicio fallido'), ('LOGOUT', 'Cierre de sesión'), ('ACCESS', 'Acceso'), ('VIEW', 'Consulta tarjeta'), ('REVEAL', 'Revelado'), ('COPY', 'Copia'), ('COPY_ATTEMPT', 'Intento de copia'), ('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DEACTIVATE', 'Desactivación'), ('DENIED', 'Acceso denegado'), ('INTEGRITY_FAILURE', 'Fallo de integridad'), ('PASSWORD_OK', 'Contraseña correcta'), ('MFA_REQUIRED', 'MFA requerido'), ('MFA_SUCCESS', 'MFA exitoso'), ('MFA_FAILED', 'MFA fallido'), ('MFA_ENROLL_START', 'Enrolamiento MFA iniciado'), ('MFA_ENROLL_COMPLETE', 'Enrolamiento MFA completado'), ('MFA_RECOVERY_USED', 'Recuperación MFA utilizada'), ('MFA_RECOVERY_REGENERATED', 'Códigos regenerados'), ('MFA_RESET', 'MFA reiniciado'), ('SESSION_CREATED', 'Sesión creada'), ('SESSION_REVOKED', 'Sesión revocada'), ('SESSION_EXPIRED', 'Sesión expirada'), ('SESSION_REPLACED', 'Sesión reemplazada'), ('DEVICE_NEW', 'Dispositivo nuevo'), ('DEVICE_TRUSTED', 'Dispositivo reconocido'), ('DEVICE_BLOCKED', 'Dispositivo bloqueado'), ('DEVICE_UNBLOCKED', 'Dispositivo desbloqueado'), ('REAUTH_SUCCESS', 'Reautenticación exitosa'), ('REAUTH_FAILED', 'Reautenticación fallida'), ('PASSWORD_CHANGED', 'Contraseña cambiada'), ('ALERT_CREATED', 'Alerta creada'), ('ALERT_REVIEWED', 'Alerta revisada'), ('ALERT_CLOSED', 'Alerta cerrada'), ('ALERT_ESCALATED', 'Alerta escalada'), ('ALERT_REOPENED', 'Alerta reabierta'), ('POLICY_CHANGED', 'Politica modificada'), ('EXCEPTION_CREATED', 'Excepcion creada'), ('EXCEPTION_REVOKED', 'Excepcion revocada'), ('EMAIL_SENT', 'Correo enviado'), ('EMAIL_FAILED', 'Fallo de correo'), ('POLICY_EVALUATION', 'Evaluacion programada'), ('CRITICAL_BLOCKED', 'Operación crítica bloqueada')], max_length=24),
        ),
    ]
