# Generated by Django 5.2.16 on 2026-07-16 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_audit_event_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGIN_FAILED', 'Inicio fallido'), ('LOGOUT', 'Cierre de sesión'), ('ACCESS', 'Acceso'), ('VIEW', 'Consulta tarjeta'), ('REVEAL', 'Revelado'), ('COPY', 'Copia'), ('COPY_ATTEMPT', 'Intento de copia'), ('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DEACTIVATE', 'Desactivación'), ('DENIED', 'Acceso denegado'), ('INTEGRITY_FAILURE', 'Fallo de integridad'), ('PASSWORD_OK', 'Contraseña correcta'), ('MFA_REQUIRED', 'MFA requerido'), ('MFA_SUCCESS', 'MFA exitoso'), ('MFA_FAILED', 'MFA fallido'), ('MFA_ENROLL_START', 'Enrolamiento MFA iniciado'), ('MFA_ENROLL_COMPLETE', 'Enrolamiento MFA completado'), ('MFA_RECOVERY_USED', 'Recuperación MFA utilizada'), ('MFA_RECOVERY_REGENERATED', 'Códigos regenerados'), ('MFA_RESET', 'MFA reiniciado'), ('SESSION_CREATED', 'Sesión creada'), ('SESSION_REVOKED', 'Sesión revocada'), ('SESSION_EXPIRED', 'Sesión expirada'), ('SESSION_REPLACED', 'Sesión reemplazada'), ('DEVICE_NEW', 'Dispositivo nuevo'), ('DEVICE_TRUSTED', 'Dispositivo reconocido'), ('DEVICE_BLOCKED', 'Dispositivo bloqueado'), ('DEVICE_UNBLOCKED', 'Dispositivo desbloqueado'), ('REAUTH_SUCCESS', 'Reautenticación exitosa'), ('REAUTH_FAILED', 'Reautenticación fallida'), ('PASSWORD_CHANGED', 'Contraseña cambiada'), ('ALERT_CREATED', 'Alerta creada'), ('ALERT_REVIEWED', 'Alerta revisada'), ('ALERT_CLOSED', 'Alerta cerrada'), ('ALERT_ESCALATED', 'Alerta escalada'), ('ALERT_REOPENED', 'Alerta reabierta'), ('POLICY_CHANGED', 'Politica modificada'), ('EXCEPTION_CREATED', 'Excepcion creada'), ('EXCEPTION_REVOKED', 'Excepcion revocada'), ('EMAIL_SENT', 'Correo enviado'), ('EMAIL_FAILED', 'Fallo de correo'), ('POLICY_EVALUATION', 'Evaluacion programada'), ('CRITICAL_BLOCKED', 'Operación crítica bloqueada'), ('REPORT_EXPORT', 'Informe exportado')], max_length=24),
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('TIMELINE', 'Línea de tiempo'), ('ALERTS', 'Alertas'), ('ACCESS', 'Accesos'), ('ADOPTION', 'Adopción'), ('CARDS', 'Tarjetas'), ('HEALTH', 'Salud operativa')], max_length=20)),
                ('export_format', models.CharField(choices=[('XLSX', 'Excel'), ('PDF', 'PDF')], max_length=8)),
                ('actor_role', models.CharField(max_length=10)),
                ('safe_filters', models.JSONField(blank=True, default=dict)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('result', models.CharField(choices=[('PENDING', 'Pendiente'), ('SUCCESS', 'Exitoso'), ('FAILED', 'Fallido'), ('LIMITED', 'Límite excedido')], default='PENDING', max_length=12)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('filename', models.CharField(blank=True, max_length=180)),
                ('safe_error', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vault_report_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='vault_report_user_date'), models.Index(fields=['report_type', 'result'], name='vault_report_type_result')],
            },
        ),
    ]
