# Generated by Django 5.2.16 on 2026-07-22 04:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_alter_auditevent_action_reportexport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='encrypted_company',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='revealgrant',
            name='internal_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGIN_FAILED', 'Inicio fallido'), ('LOGOUT', 'Cierre de sesión'), ('ACCESS', 'Acceso'), ('VIEW', 'Consulta tarjeta'), ('REVEAL', 'Revelado'), ('COPY', 'Copia'), ('COPY_ATTEMPT', 'Intento de copia'), ('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DEACTIVATE', 'Desactivación'), ('DENIED', 'Acceso denegado'), ('INTEGRITY_FAILURE', 'Fallo de integridad'), ('PASSWORD_OK', 'Contraseña correcta'), ('MFA_REQUIRED', 'MFA requerido'), ('MFA_SUCCESS', 'MFA exitoso'), ('MFA_FAILED', 'MFA fallido'), ('MFA_ENROLL_START', 'Enrolamiento MFA iniciado'), ('MFA_ENROLL_COMPLETE', 'Enrolamiento MFA completado'), ('MFA_RECOVERY_USED', 'Recuperación MFA utilizada'), ('MFA_RECOVERY_REGENERATED', 'Códigos regenerados'), ('MFA_RESET', 'MFA reiniciado'), ('SESSION_CREATED', 'Sesión creada'), ('SESSION_REVOKED', 'Sesión revocada'), ('SESSION_EXPIRED', 'Sesión expirada'), ('SESSION_REPLACED', 'Sesión reemplazada'), ('DEVICE_NEW', 'Dispositivo nuevo'), ('DEVICE_TRUSTED', 'Dispositivo reconocido'), ('DEVICE_BLOCKED', 'Dispositivo bloqueado'), ('DEVICE_UNBLOCKED', 'Dispositivo desbloqueado'), ('REAUTH_SUCCESS', 'Reautenticación exitosa'), ('REAUTH_FAILED', 'Reautenticación fallida'), ('PASSWORD_CHANGED', 'Contraseña cambiada'), ('ALERT_CREATED', 'Alerta creada'), ('ALERT_REVIEWED', 'Alerta revisada'), ('ALERT_CLOSED', 'Alerta cerrada'), ('ALERT_ESCALATED', 'Alerta escalada'), ('ALERT_REOPENED', 'Alerta reabierta'), ('POLICY_CHANGED', 'Politica modificada'), ('EXCEPTION_CREATED', 'Excepcion creada'), ('EXCEPTION_REVOKED', 'Excepcion revocada'), ('EMAIL_SENT', 'Correo enviado'), ('EMAIL_FAILED', 'Fallo de correo'), ('POLICY_EVALUATION', 'Evaluacion programada'), ('CRITICAL_BLOCKED', 'Operación crítica bloqueada'), ('REPORT_EXPORT', 'Informe exportado'), ('OPERATION_AUTHORIZED', 'Operación protegida autorizada'), ('OPERATION_WINDOW_EXPIRED', 'Autorización de operación expirada')], max_length=24),
        ),
        migrations.CreateModel(
            name='SensitiveOperationWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_hash', models.CharField(editable=False, max_length=64)),
                ('purpose', models.CharField(default='protected_data', editable=False, max_length=40)),
                ('reason', models.CharField(max_length=240)),
                ('internal_reference', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_operation_windows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='revealgrant',
            name='operation_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reveal_grants', to='vault.sensitiveoperationwindow'),
        ),
        migrations.AddIndex(
            model_name='sensitiveoperationwindow',
            index=models.Index(fields=['user', 'session_hash', 'expires_at'], name='vault_op_window_lookup'),
        ),
    ]
