# Generated by Django 5.2.16 on 2026-08-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0014_paymentcard_contact_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='brand',
            field=models.CharField(choices=[('VISA', 'Visa'), ('MC', 'Mastercard'), ('AMEX', 'American Express'), ('DINERS', 'Diners')], max_length=10),
        ),
    ]
